name: canteen_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.8
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^15.1.1
  google_fonts: ^5.1.0
  image_picker: ^1.0.4
  razorpay_flutter: ^1.3.5
  provider: ^6.0.5
  device_info_plus: ^9.1.0  # Added this package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/