name: canteen_app
description: A Flutter canteen management application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Downgrade Firebase dependencies to fix Pigeon issues
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.0
  
  # UI and design
  google_fonts: ^6.1.0
  flutter_local_notifications: ^17.2.3
  
  # Utilities
  image_picker: ^1.0.4
  razorpay_flutter: ^1.3.6
  device_info_plus: ^9.1.1
  
  # State management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true