name: canteen_app
description: A Flutter canteen management application with detailed order notifications
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies with compatible versions
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  
  # Enhanced notification dependencies
  flutter_local_notifications: ^17.2.4
  
  # Other dependencies
  shared_preferences: ^2.5.3   
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  razorpay_flutter: ^1.4.0
  device_info_plus: ^9.1.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

# Prevent dependency resolution issues
dependency_overrides: